from langchain.tools import tool
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
from langchain_core.messages import HumanMessage
import requests
import json

## when we are dealing with more then 1 tool .. and more then 1 tool are asked for execution .. then what happens is ... without getting the output of the first tool .. the llm filled the values in the second tool with its prior knowledge which affect the real time values .. hence we need to use this InjectedToolArg
from langchain_core.tools import InjectedToolArg
from typing import Annotated

load_dotenv()

@tool
def get_conversion_factor(base_currency: str, target_currency: str) -> float:
  """
  This function fetches the currency conversion factor between a given base currency and a target currency
  """
  url = f'https://v6.exchangerate-api.com/v6/c754eab14ffab33112e380ca/pair/{target_currency}/{base_currency}'

  response = requests.get(url)

  return response.json()
    

# here we had included the InjectedToolArg
# in the case of making the agent and using the Agents .. we also not need to define this annotated and injectedtoolarg
@tool
def convert(base_currency_value: int, conversion_rate: Annotated[float, InjectedToolArg]) -> float:
  """
  given a currency conversion rate this function calculates the target currency value from a given base currency value
  """

  return base_currency_value * conversion_rate

llm = ChatOpenAI()

## this is the whole workflow of the agent.. 

    # llm_with_tools = llm.bind_tools([get_conversion_factor, convert])

    # query = "What is the conversion factor between INR and USD, and based on that can you convert 10 inr to usd"

    # messages = [HumanMessage(query)]

    # ai_message = llm_with_tools.invoke(messages)

    # messages.append(ai_message)

    # ## now this will not be containing all the keys in the second toolcall as we have used the InjectedToolAnot.. as for now the value of them is not found
    # tool_calls = ai_message.tool_calls

    # for tool_call in tool_calls:
    
    #   # execute the first tool and get the value of the conversation rate 
    #   if tool_call['name'] == 'get_conversion_factor':
    #     tool_message1 = get_conversion_factor.invoke(tool_call)
    #     # fetch the conversion rate
    #     conversion_rate = json.loads(tool_message1.content)['conversion_rate']
    #     # append this tool message in the main messages list 
    #     messages.append(tool_message1)
    #   if tool_call['name'] == 'convert':
    #     # first adding the key in the args
    #     tool_call['args']['conversion_rate'] = conversion_rate
    #     tool_message2 = convert.invoke(tool_call)
    #     messages.append(tool_message2)

    # print(llm_with_tools.invoke(messages).content)


## now giving it the form of agent 
from langchain.agents import initialize_agent, AgentType

tools = [get_conversion_factor, convert]


## here the prompt is generated by its own 
## kind of old style .. and less control 
agent_executor = initialize_agent(
    tools=tools,
    llm=llm,
    agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,  # using ReAct pattern
    verbose=True  # shows internal thinking
)

user_query = "What is the value of 10 usd in inr"

response = agent_executor.invoke({'input': user_query})